version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    networks:
      - my-network

  frontend:
    build:
      context: ./frontend
    container_name: nextjs-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - my-network

networks:
  my-network:
